name: "DRM: Database 2"

on:
  workflow_call:
    inputs:
      sample:
        required: true
        type: string

jobs:
  deploy:
    name: "Grate kickoff"
    runs-on: ubuntu-latest
    steps:
    - name: "Download bundle"
      run: "echo sample: ${{ inputs.sample }}"
    - name: "Grate kickoff"
      run: "echo sample: ${{ inputs.sample }}"
