name: Obnoxious

on:
  workflow_call:
    inputs:
      sample:
        required: true
        type: string

jobs:
  obnoxious:
    runs-on: ubuntu-latest
    steps:
      - name: step-0
        run: |
          echo "sample: ${{ inputs.sample }}"
