name: Orchestrator
on:
  workflow_dispatch:
    inputs:
      sample:
        description: Bubbled-down
        required: true
        type: string

jobs:
  pfs:
    name: "PFS: All components"
    uses: ./.github/workflows/pfs-all-components.yml
    with:
      sample: ${{ inputs.sample }}

  dcp:
    name: "DCP: All components"
    uses: ./.github/workflows/dcp-all-components.yml
    with:
      sample: ${{ inputs.sample }}
