name: Component 0

on:
  workflow_call:
    inputs:
      sample:
        required: true
        type: string

jobs:
  component-0:
    runs-on: ubuntu-latest
    steps:
      - name: Step 0
        run: |
          echo "sample: ${{ inputs.sample }}"
