name: "DCP: Data Service 5"

on:
  workflow_call:
    inputs:
      sample:
        required: true
        type: string

jobs:
  deploy:
    name: "Deploy to Kubernetes"
    runs-on: ubuntu-latest
    steps:
    - name: "Download bundle"
      run: "echo sample: ${{ inputs.sample }}"
    - name: "Feed with secrets"
      run: "echo sample: ${{ inputs.sample }}"
    - name: "Kubectl apply"
      run: "echo sample: ${{ inputs.sample }}"
