name: "DCP: Data Service"

on:
  workflow_call:
    inputs:
      sample:
        required: true
        type: string

jobs:
  data-service:
    name: "DCP: Data Service"
    runs-on: ubuntu-latest
    steps:
      - name: Step 0
        run: |
          echo "sample: ${{ inputs.sample }}"
