name: "DCP: API Gateway"

on:
  workflow_call:
    inputs:
      sample:
        required: true
        type: string

jobs:
  api-gateway:
    name: "DCP: API Gateway"
    runs-on: ubuntu-latest
    steps:
      - name: Step 0
        run: |
          echo "sample: ${{ inputs.sample }}"
