name: "GTA: All components"

on:
  workflow_call:
    inputs:
      sample:
        required: true
        type: string

jobs:
  gta-data-service:
    name: "GTA: Data Service"
    uses: ./.github/workflows/gta-data-service.yml
    with:
      sample: ${{ inputs.sample }}

  gta-data-service-2:
    name: "GTA: Data Service 2"
    uses: ./.github/workflows/gta-data-service-2.yml
    with:
      sample: ${{ inputs.sample }}

  gta-data-service-3:
    needs: [gta-data-service, gta-data-service-2]
    name: "GTA: Data Service 3"
    uses: ./.github/workflows/gta-data-service-3.yml
    with:
      sample: ${{ inputs.sample }}
