name: Orchestrator
on:
  workflow_dispatch:
    inputs:
      sample:
        description: Bubbled-down
        required: true
        type: string

jobs:
  compound-a:
    uses: ./.github/workflows/pfs-all-components.yml
    with:
      sample: ${{ inputs.sample }}

#  component-theta:
#    uses: ./.github/workflows/component-theta.yml
#    with:
#      sample: ${{ inputs.sample }}
#
#  component-upsilon:
#    uses: ./.github/workflows/component-upsilon.yml
#    with:
#      sample: ${{ inputs.sample }}
