name: "PFS: All components"

on:
  workflow_call:
    inputs:
      sample:
        required: true
        type: string

jobs:
  pfs-database:
    name: "PFS: Database"
    uses: ./.github/workflows/pfs-database.yml
    with:
      sample: ${{ inputs.sample }}

  pfs-sdk:
    name: "PFS: SDK"
    uses: ./.github/workflows/pfs-sdk.yml
    with:
      sample: ${{ inputs.sample }}

  pfs-sdk-2:
    name: "PFS: SDK 2"
    uses: ./.github/workflows/pfs-sdk-2.yml
    with:
      sample: ${{ inputs.sample }}
