name: "PFS: Database"

on:
  workflow_call:
    inputs:
      sample:
        required: true
        type: string

jobs:
  pfs-database:
    name: "PFS: Database"
    runs-on: ubuntu-latest
    steps:
      - name: Step 0
        run: |
          echo "sample: ${{ inputs.sample }}"
