name: "PFS: All components"

on:
  workflow_call:
    inputs:
      sample:
        required: true
        type: string

jobs:
  pfs-database:
    uses: ./.github/workflows/pfs-database.yml
    with:
      sample: ${{ inputs.sample }}

  pfs-sdk:
    uses: ./.github/workflows/pfs-sdk.yml
    with:
      sample: ${{ inputs.sample }}
