name: "002 Orchestrator"
on:
  workflow_dispatch:
    inputs:
      sample:
        description: Bubbled-down
        required: true
        type: string

jobs:
  pfs:
    name: "PFS: All components"
    uses: ./.github/workflows/shared.yml
    with:
      sample: ${{ inputs.sample }}
      name: "pfs"
